### ISSUE TITLE
Cannot install PHP8.2 with Pantheon Recipe

### ISSUE THREAD

**Issue by CarlosBlackSmith** [lando/pantheon#232] opened 2023-08-16 20:07 UTC
Trying to upgrade my site to 8.2 in Pantheon, changed  php_version: 8.2 in pantheon.yml tried rebuilding and lando destroy, lando init and lando start and got errors
Pulling appserver (devwithlando/pantheon-appserver:8.2-4)...
Traceback (most recent call last):
  File "docker/credentials/store.py", line 80, in _execute
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 488, in run
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1551, in _execute_child
OSError: [Errno 8] Exec format error: '/mnt/c/Program Files/Docker/Docker/resources/bin/docker-credential-desktop.exe'

During handling of the above exception, another exception occurred:

going back to a different php version works ok

Windows 11/Wsl2 all updated by Aug/2023

**Comment by reynoldsalec** [comment] 2024-04-02 17:04
Steps to attempt replication:

1. Spin up (or `lando init` an existing Pantheon project) on a WSL2 instance. It's possible the user is running Docker Desktop OR WSL2 with Docker CE custom installed...we don't need to specifically test either scenario.
2. Make sure PHP `8.2` is selected in the `pantheon.yml`
3. Run `lando start` (or `lando rebuild` if the project was already running)

If unable to reproduce, I'd recommend closing this out unless OP has more details/solution.

**Comment by oskarmodig** [comment] 2024-04-03 08:04
FWIW, I tried setting up a new Patheon project with Lando, and it seemingly runs without issues. Confirmed php was running version 8.2.

- Windows 11
- Lando v3.21.0-beta.12
- Docker Desktop 4.23.0 with WSL integration enabled

@CarlosBlackSmith, is this still an issue for you?

**Comment by reynoldsalec** [comment] 2024-04-09 03:53
If we haven't been able to replicate, going to close this out but @CarlosBlackSmith definitely ping us here (or on Slack) if you're having further issues!

**Closed by reynoldsalec** 2024-04-09 03:53 UTC
Labels: good first issue, question
